version: "3.8"
services:
  db:
    image: mongo:4.2
    container_name: db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - ./data/dump:/dump

  backend:
    build:
      context: /var/lib/jenkins/workspace/ProjectManagment/backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    ports:
      - "5001:5001"

 