version: '3.8'
services:
  db:
    image: mongo:4.2
    container_name: db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: Dreamtim
      MONGO_INITDB_ROOT_PASSWORD: Dreamtim
    ports:
      - 27017:27017
    volumes:
      - ./data/dump:/dump
  app:
    build: .
    image: 192.168.33.10:8083/nodemongoapp:6.0
    restart: always
    container_name: back
    ports:
      - '5001:5001'  # Modifier le port externe à 5001
    depends_on:
      - db
    volumes:
      - mongo-data
