pipeline {
    agent any
    tools{
        nodejs '21.6.2'
    }

    stages {
        stage('Checkout and Install dependencies') {
            steps {
                script {
                    // Check out the repository
                    checkout scm

                    // Install dependencies inside the 'backend' directory
                    dir('backend') {
                        sh 'npm install'
                    }
                }
            }
        }

        stage('Unit Test') {
            steps {
                script {
                    // Run unit tests (customize as needed)
                    dir('backend') {
                        sh 'npm test'
                    }
                }
            }
        }

        stage('Build application') {
            steps {
                script {
                    // Build the application (customize as needed)
                    dir('backend') {
                        sh 'npm run build-dev'
                    }
                }
            }
        }
    }
}
