pipeline {
    agent any

    tools {
        nodejs 'NodeJs'
    }

    stages {
        stage('Install dependencies') {
            steps {
                script {
                    try {
                        dir('C:\\Users\\user\\Desktop\\ProjectManagementPi\\backend') {
                            // Change directory to where package.json is located
                            sh 'npm install'
                        }
                    } catch (err) {
                        currentBuild.result = 'FAILURE'
                        error("Failed to install dependencies: ${err}")
                    }
                }
            }
        }

        stage('Unit Test') {
            steps {
                script {
                    echo 'Running unit tests...'
                    // Add your unit testing commands here
                }
            }
        }
    }
}
